RSpec.describe Mapper::DefaultMapper do

  FORMATTED = [
      {:evid => "966634dc-0bf6-1ff7-f4b6-08000c95c670", :vendor_site_id => "209", :vendor_visit_id => "134853732", :vendor_visitor_id => "e280af5191b64f18", :actionDetails => [{:url => "https://apptest.loanspq.com/vl/VehicleLoan.aspx/vehicle-loan-information?lenderref=Meriwest_test&l=1", :title => "Vehicle Loan Information", :time_spent => "50", :timestamp => 1537623918, :position => 0}, {:url => "https://apptest.loanspq.com/vl/VehicleLoan.aspx/vehicle-loan-information?lenderref=Meriwest_test&l=1", :title => "Vehicle Loan Information", :time_spent => "1", :timestamp => 1537623579, :position => 1}, {:url => "https://apptest.loanspq.com/vl/VehicleLoan.aspx/vehicle-loan-information?lenderref=Meriwest_test&l=1", :title => "Vehicle Loan Information", :time_spent => "337", :timestamp => 1537623580, :position => 2}, {:url => "https://apptest.loanspq.com/vl/VehicleLoan.aspx/vehicle-loan-information?lenderref=Meriwest_test&l=1", :title => "Vehicle Loan Information", :time_spent => "1", :timestamp => 1537623917, :position => 3}, {:url => "https://apptest.loanspq.com/vl/VehicleLoan.aspx/vehicle-loan-information?lenderref=Meriwest_test&l=1", :title => "Vehicle Loan Information", :time_spent => "50", :timestamp => 1537623918, :position => 4}, {:url => "https://apptest.loanspq.com/vl/VehicleLoan.aspx/vehicle-loan-information?lenderref=Meriwest_test&time=1-45-pm&l=1", :title => "Vehicle Loan Information", :time_spent => "1", :timestamp => 1537623968, :position => 5}, {:url => "https://apptest.loanspq.com/vl/VehicleLoan.aspx/vehicle-loan-information?lenderref=Meriwest_test&time=1-45-pm&l=1", :title => "Vehicle Loan Information", :time_spent => "463", :timestamp => 1537623969, :position => 6}, {:url => "https://apptest.loanspq.com/vl/VehicleLoan.aspx/vehicle-loan-information?lenderref=Meriwest_test&l=1", :title => "Vehicle Loan Information", :time_spent => "1", :timestamp => 1537624432, :position => 7}, {:url => "https://apptest.loanspq.com/vl/VehicleLoan.aspx/vehicle-loan-information?lenderref=Meriwest_test&l=1", :title => "Vehicle Loan Information", :time_spent => "1161", :timestamp => 1537624433, :position => 8}, {:url => "https://apptest.loanspq.com/vl/VehicleLoan.aspx/vehicle-loan-information?lenderref=Meriwest_test&evid=evid&l=1", :title => "Vehicle Loan Information", :time_spent => "1", :timestamp => 1537625594, :position => 9}, {:url => "https://apptest.loanspq.com/vl/VehicleLoan.aspx/vehicle-loan-information?lenderref=Meriwest_test&evid=evid&l=1", :title => "Vehicle Loan Information", :time_spent => nil, :timestamp => 1537625595, :position => 10}], :visit_ip => "24.6.5.33"},
      {:evid => "", :vendor_site_id => "209", :vendor_visit_id => "134853338", :vendor_visitor_id => "e280af5191b64f18", :actionDetails => [{:url => "https://apptest.loanspq.com/vl/VehicleLoan.aspx/alert-popup?lenderref=Meriwest_test&evid=12-56-pm&l=1", :title => "Alert Popup", :time_spent => "15", :timestamp => 1537623145, :position => 0}, {:url => "https://apptest.loanspq.com/vl/VehicleLoan.aspx/applicant-information?lenderref=Meriwest_test&evid=12-56-pm&l=1", :title => "Applicant Information", :time_spent => "1", :timestamp => 1537623160, :position => 1}, {:url => "https://apptest.loanspq.com/vl/VehicleLoan.aspx/applicant-information?lenderref=Meriwest_test&evid=12-56-pm&l=1", :title => "Applicant Information", :time_spent => "3", :timestamp => 1537623161, :position => 2}, {:url => "https://apptest.loanspq.com/vl/VehicleLoan.aspx/vehicle-loan-information?lenderref=Meriwest_test&evid=12-56-pm&l=1", :title => "Vehicle Loan Information", :time_spent => "1", :timestamp => 1537623164, :position => 3}, {:url => "https://apptest.loanspq.com/vl/VehicleLoan.aspx/vehicle-loan-information?lenderref=Meriwest_test&evid=12-56-pm&l=1", :title => "Vehicle Loan Information", :time_spent => nil, :timestamp => 1537623165, :position => 4}], :visit_ip => "24.6.5.33"},
      {:evid => "3385a27a-cc20-8d98-940a-37dad5a93133", :vendor_site_id => "209", :vendor_visit_id => "134849628", :vendor_visitor_id => "e280af5191b64f18", :actionDetails => [{:url => "https://apptest.loanspq.com/vl/VehicleLoan.aspx/vehicle-loan-information?lenderref=Meriwest_test&l=1", :title => "Vehicle Loan Information", :time_spent => "368", :timestamp => 1537619480, :position => 0}, {:url => "https://apptest.loanspq.com/vl/VehicleLoan.aspx/applicant-information?lenderref=Meriwest_test&l=1", :title => "Applicant Information", :time_spent => "1229", :timestamp => 1537619848, :position => 1}, {:url => "https://apptest.loanspq.com/vl/VehicleLoan.aspx/vehicle-loan-information?lenderref=Meriwest_test&evid=12-56-pm&l=1", :title => "Vehicle Loan Information", :time_spent => "0", :timestamp => 1537621077, :position => 2}, {:url => "https://apptest.loanspq.com/vl/VehicleLoan.aspx/vehicle-loan-information?lenderref=Meriwest_test&evid=12-56-pm&l=1", :title => "Vehicle Loan Information", :time_spent => "123", :timestamp => 1537621077, :position => 3}, {:url => "https://apptest.loanspq.com/vl/VehicleLoan.aspx/applicant-information?lenderref=Meriwest_test&evid=12-56-pm&l=1", :title => "Applicant Information", :time_spent => nil, :timestamp => 1537621200, :position => 4}], :visit_ip => "24.6.5.33"},
      {:evid => "", :vendor_site_id => "209", :vendor_visit_id => "134843051", :vendor_visitor_id => "e280af5191b64f18", :actionDetails => [{:url => "https://apptest.loanspq.com/pl/PersonalLoan.aspx/personal-loan-information?lenderref=Meriwest_test&l=1", :title => "Personal Loan Information", :time_spent => "1", :timestamp => 1537613572, :position => 0}, {:url => "https://apptest.loanspq.com/vl/VehicleLoan.aspx/vehicle-loan-information?lenderref=Meriwest_test&rec=1&uid=evid_808asdfaasdv7a6s5dasdfva7s8d6f&l=1", :title => "Vehicle Loan Information", :time_spent => "1075", :timestamp => 1537614509, :position => 1}, {:url => "https://apptest.loanspq.com/pl/PersonalLoan.aspx/personal-loan-information?lenderref=Meriwest_test&l=1", :title => "Personal Loan Information", :time_spent => "734", :timestamp => 1537613573, :position => 2}, {:url => "https://apptest.loanspq.com/vl/VehicleLoan.aspx/vehicle-loan-information?lenderref=Meriwest_test&l=1", :title => "Vehicle Loan Information", :time_spent => "1", :timestamp => 1537614307, :position => 3}, {:url => "https://apptest.loanspq.com/vl/VehicleLoan.aspx/vehicle-loan-information?lenderref=Meriwest_test&l=1", :title => "Vehicle Loan Information", :time_spent => "200", :timestamp => 1537614308, :position => 4}, {:url => "https://apptest.loanspq.com/vl/VehicleLoan.aspx/vehicle-loan-information?lenderref=Meriwest_test&rec=1&uid=evid_808asdfaasdv7a6s5dasdfva7s8d6f&l=1", :title => "Vehicle Loan Information", :time_spent => "1", :timestamp => 1537614508, :position => 5}, {:url => "https://apptest.loanspq.com/vl/VehicleLoan.aspx/vehicle-loan-information?lenderref=Meriwest_test&cb-vid=64c1f015-00ea-f186-6bb8-c545347e3075&l=1", :title => "Vehicle Loan Information", :time_spent => "0", :timestamp => 1537615584, :position => 6}, {:url => "https://apptest.loanspq.com/vl/VehicleLoan.aspx/vehicle-loan-information?lenderref=Meriwest_test&cb-vid=64c1f015-00ea-f186-6bb8-c545347e3075&l=1", :title => "Vehicle Loan Information", :time_spent => nil, :timestamp => 1537615584, :position => 7}], :visit_ip => "24.6.5.33"}
  ].freeze
  describe '.call' do

    it 'returns error' do
      mapper = Mapper::DefaultMapper.new
      fetch_result = Fetcher::FakeFetcher.call(nil, nil).unwrap
      data = mapper.call(JSON.parse(fetch_result[:data]))
      expect(data).to eq(FORMATTED)
    end
  end
end
